name: SkyShop
version: '1.0.0'
main: de.laurinhummel.skyshop.Main
api-version: 1.16
load: POSTWORLD
depend: [ Vault, Essentials ]
authors: [ SkyExit, JoeJoeSpielt ]
description: Your n°1 Shop Plugin
website: laurinhummel.de


commands:
  shop:
    description: Shop
  econ:
    description: Economy
